name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SwiftyLab/setup-swift@latest
        with:
          development: true
      - run: swift test --parallel
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
